language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.1
env:
  - MIX_ENV=test
otp_release:
  - 19.3
  - 20.3
  - 21.2
cache:
  directories:
    - _build
    - deps
before_script:
  - mix compile
  - travis_wait mix dialyzer --plt
script:
  - mix test
  - mix dialyzer --halt-exit-status
